package io.euphoria.xkcd.app.ui

import io.euphoria.xkcd.app.connection.ConnectionStatus
import io.euphoria.xkcd.app.data.Message
import io.euphoria.xkcd.app.data.SessionView

/** Created by Xyzzy on 2017-02-24.  */ /* POJO wrapper around the UI corresponding to a room */
interface RoomUI {
    /* The name of the room */
    val roomName: String

    /* Show this UI, possibly putting it in front of others */
    fun show()

    /* Close the room UI
     *
     * After closing, the object should be considered unusable.
     */
    fun close()

    /* Update the connection status of the UI
     *
     * The serves as feed-back to the user.
     */
    fun setConnectionStatus(status: ConnectionStatus)

    /* Display the given messages
     *
     * If a message in the list is already visible (as determined by the message ID), it is to be replaced.
     */
    fun showMessages(messages: List<Message>)

    /* Update the nickname list with the given session ID-name pairs
     *
     * Changed nicknames are to be replaced. Empty nicknames are not to be shown.
     */
    fun showNicks(sessions: List<SessionView>)

    /* Remove the nickname list entries with the given session ID-s */
    fun removeNicks(sessions: List<SessionView>)

    /* Listen for events generated by the UI */
    fun addEventListener(l: UIListener)

    /* Remove an event listener */
    fun removeEventListener(l: UIListener)
}
