package io.euphoria.xkcd.app.ui;

import java.util.List;

import io.euphoria.xkcd.app.connection.ConnectionStatus;
import io.euphoria.xkcd.app.data.Message;
import io.euphoria.xkcd.app.data.SessionView;

/** Created by Xyzzy on 2017-02-24. */

/* POJO wrapper around the UI corresponding to a room */
public interface RoomUI {

    /* The name of the room */
    String getRoomName();

    /* Show this UI, possibly putting it in front of others */
    void show();

    /* Close the room UI
     *
     * After closing, the object should be considered unusable.
     */
    void close();

    /* Update the connection status of the UI
     *
     * The serves as feed-back to the user.
     */
    void setConnectionStatus(ConnectionStatus status);

    /* Display the given messages
     *
     * If a message in the list is already visible (as determined by the message ID), it is to be replaced.
     */
    void showMessages(List<Message> messages);

    /* Update the nickname list with the given session ID-name pairs
     *
     * Changed nicknames are to be replaced. Empty nicknames are not to be shown.
     */
    void showNicks(List<SessionView> sessions);

    /* Remove the nickname list entries with the given session ID-s */
    void removeNicks(List<SessionView> sessions);

    /* Listen for events generated by the UI */
    void addEventListener(UIListener l);

    /* Remove an event listener */
    void removeEventListener(UIListener l);

}
